alias: RNN
batch_size: 64
callbacks:
- !!python/object:pytorch_lightning.callbacks.progress.tqdm_progress.TQDMProgressBar
  _current_eval_dataloader_idx: null
  _enabled: true
  _predict_progress_bar: null
  _process_position: 0
  _refresh_rate: 1
  _test_progress_bar: null
  _train_progress_bar: null
  _trainer: null
  _val_progress_bar: null
- !!python/object:ray.tune.integration.pytorch_lightning.TuneReportCallback
  _filename: checkpoint
  _metrics:
    loss: ptl/val_loss
  _on:
  - on_validation_end
  _save_checkpoints: false
context_size: 10
decoder_hidden_size: 200
decoder_layers: 2
drop_last_loader: false
early_stop_patience_steps: -1
encoder_activation: tanh
encoder_bias: true
encoder_dropout: 0.2
encoder_hidden_size: 200
encoder_n_layers: 2
futr_exog_list: null
h: 1
hist_exog_list: null
inference_input_size: -1
input_size: 128
learning_rate: 0.0001
loss: &id001 !!python/object:neuralforecast.losses.pytorch.MSE
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - []
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  horizon_weight: null
  is_distribution_output: false
  output_names:
  - ''
  outputsize_multiplier: 1
  training: true
max_steps: 1000
num_lr_decays: -1
num_workers_loader: 0
random_seed: 1
scaler_type: robust
stat_exog_list: null
val_check_steps: 100
valid_batch_size: null
valid_loss: *id001
